name: falkit
description: A new Flutter package project.
version: 1.1.7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: 1.0.13

  #PLATFORM: All
  gap: ^3.0.1
  flutter_svg: ^2.0.16
  extended_image: ^9.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
